name: WCA database export

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    env:
      DB_LINK: https://www.worldcubeassociation.org/export/results/WCA_export.sql

      DB_HOST: 127.0.0.1
      DB_PORT: 8888
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: wca

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and extract WCA database
        run: |
          curl -L $DB_LINK -o WCA_export.zip
          unzip WCA_export.zip -d WCA_export
          sed -i "1d" WCA_export/WCA_export.sql

      - name: Populate database
        run: |
          mysql -h $DB_HOST --port $DB_PORT -u $DB_USER -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
          mysql -h $DB_HOST --port $DB_PORT -u $DB_USER -p$DB_PASSWORD $DB_NAME < WCA_export/WCA_export.sql

      - name: Delete files
        run: rm -rf WCA_export

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Extract data
        run: npm run export

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update: wca data"
          title: Update WCA data
          body: Auto-generated by create-pull-request
          branch: update-wca-data
